### ISSUE TITLE
Problème de routes

### ISSUE THREAD

**Issue by ouatedephoque** [ouatedephoque/projetLaravel#2]
Dans la branche "testLaravel" j'ai créer un nouveau projet laravel afin d'explorer ce framework.

Lorsque je désire créer plusieurs routes pointant sur des urls différentes, je n'arrive pas à suivre ces routes en tapant l'url dans le navigateur. La seul route que j'arrive à suivre est la route par défaut ("/").

Je devrais pourtant pouvoir suivre la route "/about" en tapant dans mon url "localhost/.../about"

**Comment by greut** [comment]
@ouatedephoque cool! Et ça donne quoi sur srvz-webapp? Vous pouvez commencer par suivre les instructions du fichier [`README.md`](https://github.com/HE-Arc/webapp-server/blob/master/files/templates/README.md) que vous trouverez sur votre machine.

```
$ ssh -p 2205 jeshon@srvz-webapp.he-arc.ch
$ more README.md
```

Ce genre de problème est souvent lié à la [réécriture d'URL](https://github.com/HE-Arc/php-intro-framework#r%C3%A9%C3%A9criture-durl) qui n'est pas correctement activée/configurée.

**Comment by greut** [comment]
Ce que j'ai tenté de faire:

```
$ ssh srvz...
$ cd www
$ git clone ...
$ cd projetLaravel
$ git checkout origin/testLaravel
$ composer install
$ # config nginx and restart it
```

![tournoi](https://cloud.githubusercontent.com/assets/1388/10552840/d60905c8-7456-11e5-9eba-d1d1e81b709c.png)

Le problème est que vous avez deux applications: `app` et `myFirstLaravelApp`. La première est au format Laravel 4.2 (Novembre 2014) et l'autre Laravel 5.1 (Juin 2015). La première est celle active et ne contient pas de `about`, et la seconde ne fonctionne pas car incompatible (voir capture d'écran ci-dessus).

## :warning: Nitrous n'est pas que votre ami.

**Nitrous**

``` shell
$ php -v
PHP 5.5.9-1ubuntu4.11 (cli) (built: Jul  2 2015 15:23:08)
$ grep laravel/framework composer.json
        "laravel/framework": "4.2.*"
```

**SRVZ**

``` shell
$ php -v
PHP 5.6.4-4ubuntu6.3 (cli) (built: Sep 29 2015 12:44:47)
$ lavarel new blog
$ grep laravel/framework blog/composer.json
        "laravel/framework": "5.1.*"
```

## Conseil

Prenez le temps d'apprendre à mettre en oeuvre un serveur web, ça risque de vous être utile par la suite. On ne sait jamais, d'un coup qu'Internet devienne populaire.

**Comment by greut** [comment]
@ouatedephoque ping

**Comment by ouatedephoque** [comment]
Le problème ne venait pas de là. Vous n'aviez pas bien saisi le soucis, mais je m'en suis sortie en cherchant un peu (beaucoup) plus profondément sur le web. 
En effet, je vous parlais de test en local, je n'ai pas utilisé Nitrous ou le serveur srvz-webapp.he-arc.ch pour effectuer ces petits tests. Le problème ne peut donc pas provenir de là.

Il fallait en fait activer le module Rewrite sur le serveur apache local et lancer la commande "php -S localhost:8888 -t public" afin que le serveur apache écoute sur "http://localhost/8888" et que le document root soit bien le dossier "public" de mon application Laravel.

Merci pour votre aide, ces quelques conseils pourront quand même m'être utile pour la suite !

**Comment by greut** [comment]
Vous êtes chou tout plein.

> Ce genre de problème est souvent lié à la [réécriture d'URL](https://github.com/HE-Arc/php-intro-framework#r%C3%A9%C3%A9criture-durl) qui n'est pas correctement activée/configurée.
> --  @greut commented 4 days ago
