### ISSUE TITLE
Formulaire de tournoi

### ISSUE THREAD

**Issue by YohskDista** [ouatedephoque/projetLaravel#5]
Création d'un formulaire permettant la création de tournoi. 
La personne devra dans un premier temps inscrire le nom de son tournoi. Une fois fait elle sera rediriger sur cette page de formulaire.
Ce formulaire permettra d'indiquer : 
- Le nombre d'équipes ainsi que leur nom.
- Le type du tournoi (par groupe ou élimination direct)
- Nombre de terrains disponible pour ce tournoi
- Le temps que dure un match
- Le temps de battement entre chaque matchs (changement d'équipes sur les terrains)
- La pause pour le repas

Une fois ce formulaire valider, le tournoi sera enregistré (ainsi que les équipes) et l'utilisateur sera redirigé vers une page de gestion de tournoi

**Comment by greut** [comment]
@leonardodistasio il y a un bouton "close" pour marquer une tâche comme étant terminée.

**Comment by greut** [comment]
:+1:
